# Generated by Django 4.2.17 on 2025-01-21 12:08

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_alter_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default-post_zku7kd', max_length=255, verbose_name='image'),
        ),
    ]
