# Generated by Django 4.2.17 on 2025-01-23 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_post_likes_alter_post_image'),
    ]

