# Generated by Django 4.2.17 on 2025-01-21 10:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dnrw0c882/image/upload/v1737455301/default-profile_mzguyn.jpg', max_length=255, verbose_name='image'),
        ),
    ]
